name: Build and Deploy to Azure Container Apps

on:
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_REGISTRY }}.azurecr.io
  CONTAINER_APP_NAME: ca-demoflask-staging
  RESOURCE_GROUP: rg-demoflask-staging-northeurope
  IMAGE_NAME: flask-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURECREDS }}

      - name: Login to ACR
        run: az acr login --name demoflask

      - name: Build and push image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Container Apps
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}