name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [master-disabled]

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.ACR_REGISTRY }}.azurecr.io
  CONTAINER_APP_NAME: demo_flask
  RESOURCE_GROUP: flask-app
  IMAGE_NAME: flask-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_REGISTRY }}

      - name: Build and push image
        run: |
          docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }} .
          docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy to Container Apps
        run: |
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:${{ github.sha }}